// Generated by CodiumAI

import { render, screen } from "@testing-library/react";
import Logo from ".";

describe("Logo", () => {
  it("should render an Image component with the correct props", () => {
    render(<Logo />);
    const image = screen.getByAltText("logo");
    expect(image).toBeInTheDocument();
  });
});
